apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sam-mesh.fullname" . }}-control-plane
  labels:
    {{- include "sam-mesh.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controlPlane.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sam-mesh.fullname" . }}-control-plane
  template:
    metadata:
      labels:
        app: {{ include "sam-mesh.fullname" . }}-control-plane
    spec:
      containers:
      - name: sam-control-plane
        image: "{{ .Values.controlPlane.image.repository }}:{{ .Values.global.imageTag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "sam-mesh.fullname" . }}-secrets
              key: db-password
        - name: SAM_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "sam-mesh.fullname" . }}-secrets
              key: admin-token
        ports:
        - containerPort: 8080
          name: http
          {{- if .Values.controlPlane.hostPort }}
          hostPort: {{ .Values.controlPlane.hostPort }}
          {{- end }}
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 15
        resources:
          {{- toYaml .Values.controlPlane.resources | nindent 10 }}
        args:
        - "--bind-address=0.0.0.0:8080"
        {{- if eq .Values.database.type "postgres" }}
        - "--db-driver=postgres"
        {{- $dbHost := printf "%s-db" (include "sam-mesh.fullname" .) }}
        {{- if not .Values.database.postgres.deployInternal }}
          {{- $dbHost = .Values.database.postgres.host }}
        {{- end }}
        - "--db-dsn=postgres://{{ .Values.database.postgres.user }}:$(DB_PASSWORD)@{{ $dbHost }}:{{ .Values.database.postgres.port | default 5432 }}/{{ .Values.database.postgres.database }}?sslmode={{ .Values.database.postgres.sslmode | default "disable" }}"
        {{- else }}
        - "--db-driver=sqlite"
        - "--db-dsn=/data/control-plane.db"
        {{- end }}
        - "--issuer={{ .Values.controlPlane.oidcIssuer }}"
        - "--allowed-audiences={{ .Values.controlPlane.allowedAudiences }}"
        {{- if .Values.controlPlane.autoApproveEnrollment }}
        - "--auto-approve-enrollment"
        {{- end }}
        {{- if .Values.controlPlane.insecureSkipTlsVerify }}
        - "--insecure-skip-tls-verify"
        {{- end }}
        - "--log-level={{ .Values.controlPlane.logLevel }}"
