{{- if .Values.dex.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sam-mesh.fullname" . }}-dex-config
  labels:
    {{- include "sam-mesh.labels" . | nindent 4 }}
data:
  config.yaml: |
    issuer: http://{{ include "sam-mesh.fullname" . }}-dex:5556/dex
    storage:
      type: memory
    web:
      http: 0.0.0.0:5556
    oauth2:
      skipApprovalScreen: true
    staticClients:
    - id: sam-console
      redirectURIs:
      - http://localhost:9092/auth/callback
      - http://127.0.0.1:9092/auth/callback
      name: 'SAM Console'
      public: true
    enablePasswordDB: true
    staticPasswords:
    - email: admin@example.com
      # bcrypt hash for 'password'
      hash: "$2a$10$TUOgJVdtu0AL6Y6TcNBQXOSjRWRKhIkC0kXDzN9kOkPB4hg2aFPE2"
      username: admin
      userID: "0898fa90-3453-4311-8566-020953250212"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sam-mesh.fullname" . }}-dex
  labels:
    {{- include "sam-mesh.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sam-mesh.fullname" . }}-dex
  template:
    metadata:
      labels:
        app: {{ include "sam-mesh.fullname" . }}-dex
    spec:
      nodeSelector:
        sam-role: control-plane
      containers:
      - name: dex
        image: "{{ .Values.dex.image.repository }}:{{ .Values.dex.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        args:
        - dex
        - serve
        - /etc/dex/cfg/config.yaml
        ports:
        - containerPort: 5556
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
      volumes:
      - name: config
        configMap:
          name: {{ include "sam-mesh.fullname" . }}-dex-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sam-mesh.fullname" . }}-dex
  labels:
    {{- include "sam-mesh.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: {{ include "sam-mesh.fullname" . }}-dex
  ports:
  - name: http
    port: 5556
    targetPort: 5556
    {{- if .Values.dex.nodePort }}
    nodePort: {{ .Values.dex.nodePort }}
    {{- end }}
{{- end }}
