// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/sam.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollmentStatus int32

const (
	EnrollmentStatus_ENROLLMENT_STATUS_UNSPECIFIED EnrollmentStatus = 0
	EnrollmentStatus_ENROLLMENT_STATUS_PENDING     EnrollmentStatus = 1
	EnrollmentStatus_ENROLLMENT_STATUS_APPROVED    EnrollmentStatus = 2
	EnrollmentStatus_ENROLLMENT_STATUS_REJECTED    EnrollmentStatus = 3
)

// Enum value maps for EnrollmentStatus.
var (
	EnrollmentStatus_name = map[int32]string{
		0: "ENROLLMENT_STATUS_UNSPECIFIED",
		1: "ENROLLMENT_STATUS_PENDING",
		2: "ENROLLMENT_STATUS_APPROVED",
		3: "ENROLLMENT_STATUS_REJECTED",
	}
	EnrollmentStatus_value = map[string]int32{
		"ENROLLMENT_STATUS_UNSPECIFIED": 0,
		"ENROLLMENT_STATUS_PENDING":     1,
		"ENROLLMENT_STATUS_APPROVED":    2,
		"ENROLLMENT_STATUS_REJECTED":    3,
	}
)

func (x EnrollmentStatus) Enum() *EnrollmentStatus {
	p := new(EnrollmentStatus)
	*p = x
	return p
}

func (x EnrollmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrollmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sam_proto_enumTypes[0].Descriptor()
}

func (EnrollmentStatus) Type() protoreflect.EnumType {
	return &file_api_sam_proto_enumTypes[0]
}

func (x EnrollmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrollmentStatus.Descriptor instead.
func (EnrollmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{0}
}

type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_UNSPECIFIED ServiceType = 0
	ServiceType_SERVICE_TYPE_MCP         ServiceType = 1
	ServiceType_SERVICE_TYPE_INFERENCE   ServiceType = 2
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "SERVICE_TYPE_MCP",
		2: "SERVICE_TYPE_INFERENCE",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED": 0,
		"SERVICE_TYPE_MCP":         1,
		"SERVICE_TYPE_INFERENCE":   2,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sam_proto_enumTypes[1].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_api_sam_proto_enumTypes[1]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{1}
}

type MeshEvent_Type int32

const (
	MeshEvent_BANNED        MeshEvent_Type = 0
	MeshEvent_KEY_ROTATION  MeshEvent_Type = 1
	MeshEvent_POLICY_UPDATE MeshEvent_Type = 2
)

// Enum value maps for MeshEvent_Type.
var (
	MeshEvent_Type_name = map[int32]string{
		0: "BANNED",
		1: "KEY_ROTATION",
		2: "POLICY_UPDATE",
	}
	MeshEvent_Type_value = map[string]int32{
		"BANNED":        0,
		"KEY_ROTATION":  1,
		"POLICY_UPDATE": 2,
	}
)

func (x MeshEvent_Type) Enum() *MeshEvent_Type {
	p := new(MeshEvent_Type)
	*p = x
	return p
}

func (x MeshEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeshEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sam_proto_enumTypes[2].Descriptor()
}

func (MeshEvent_Type) Type() protoreflect.EnumType {
	return &file_api_sam_proto_enumTypes[2]
}

func (x MeshEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeshEvent_Type.Descriptor instead.
func (MeshEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{2, 0}
}

type AuthFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Biscuit       []byte                 `protobuf:"bytes,1,opt,name=biscuit,proto3" json:"biscuit,omitempty"`
	TargetService string                 `protobuf:"bytes,2,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"` // Optional: specific service requested
	// The agent this request is made for, as a canonical agent identifier (see
	// api/agent.go). It is the calling node's claim, carried beside the token
	// because Biscuit hides an appended block's facts from the authorizer; the
	// HTTP datapath carries the same claim in HeaderSamAgent.
	Agent         string `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthFrame) Reset() {
	*x = AuthFrame{}
	mi := &file_api_sam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthFrame) ProtoMessage() {}

func (x *AuthFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthFrame.ProtoReflect.Descriptor instead.
func (*AuthFrame) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{0}
}

func (x *AuthFrame) GetBiscuit() []byte {
	if x != nil {
		return x.Biscuit
	}
	return nil
}

func (x *AuthFrame) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *AuthFrame) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`     // populated only if success is false
	Biscuit       []byte                 `protobuf:"bytes,3,opt,name=biscuit,proto3" json:"biscuit,omitempty"` // The server's own Biscuit token (for mutual auth)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_api_sam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthResponse) GetBiscuit() []byte {
	if x != nil {
		return x.Biscuit
	}
	return nil
}

type MeshEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MeshEvent_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=sam.v1.MeshEvent_Type" json:"type,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NewPublicKey  []byte                 `protobuf:"bytes,4,opt,name=new_public_key,json=newPublicKey,proto3" json:"new_public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshEvent) Reset() {
	*x = MeshEvent{}
	mi := &file_api_sam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshEvent) ProtoMessage() {}

func (x *MeshEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshEvent.ProtoReflect.Descriptor instead.
func (*MeshEvent) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{2}
}

func (x *MeshEvent) GetType() MeshEvent_Type {
	if x != nil {
		return x.Type
	}
	return MeshEvent_BANNED
}

func (x *MeshEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *MeshEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MeshEvent) GetNewPublicKey() []byte {
	if x != nil {
		return x.NewPublicKey
	}
	return nil
}

func (x *MeshEvent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	RequestedRole string                 `protobuf:"bytes,4,opt,name=requested_role,json=requestedRole,proto3" json:"requested_role,omitempty"`
	// Operator-declared labels (e.g. key "region", see api/labels.go).
	// Validated fail-closed by the control plane and, once attested by the
	// enrollment flow's gates, minted as signed label() facts in the
	// biscuit. Empty means no claims.
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_api_sam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *EnrollRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *EnrollRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *EnrollRequest) GetRequestedRole() string {
	if x != nil {
		return x.RequestedRole
	}
	return ""
}

func (x *EnrollRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type EnrollResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BiscuitToken          []byte                 `protobuf:"bytes,1,opt,name=biscuit_token,json=biscuitToken,proto3" json:"biscuit_token,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ControlPlanePublicKey []byte                 `protobuf:"bytes,3,opt,name=control_plane_public_key,json=controlPlanePublicKey,proto3" json:"control_plane_public_key,omitempty"`
	RouterAddresses       []string               `protobuf:"bytes,4,rep,name=router_addresses,json=routerAddresses,proto3" json:"router_addresses,omitempty"`
	Expiration            int64                  `protobuf:"varint,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_api_sam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollResponse) GetBiscuitToken() []byte {
	if x != nil {
		return x.BiscuitToken
	}
	return nil
}

func (x *EnrollResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *EnrollResponse) GetControlPlanePublicKey() []byte {
	if x != nil {
		return x.ControlPlanePublicKey
	}
	return nil
}

func (x *EnrollResponse) GetRouterAddresses() []string {
	if x != nil {
		return x.RouterAddresses
	}
	return nil
}

func (x *EnrollResponse) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

type BootstrapEnrollRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BootstrapToken string                 `protobuf:"bytes,1,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	PeerId         string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PublicKey      []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	RequestedRole  string                 `protobuf:"bytes,4,opt,name=requested_role,json=requestedRole,proto3" json:"requested_role,omitempty"`
	// Operator-declared labels; the admin approving the enrollment attests
	// them (see EnrollRequest.labels).
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapEnrollRequest) Reset() {
	*x = BootstrapEnrollRequest{}
	mi := &file_api_sam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapEnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapEnrollRequest) ProtoMessage() {}

func (x *BootstrapEnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapEnrollRequest.ProtoReflect.Descriptor instead.
func (*BootstrapEnrollRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{5}
}

func (x *BootstrapEnrollRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *BootstrapEnrollRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *BootstrapEnrollRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *BootstrapEnrollRequest) GetRequestedRole() string {
	if x != nil {
		return x.RequestedRole
	}
	return ""
}

func (x *BootstrapEnrollRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type BootstrapEnrollResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Status                EnrollmentStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=sam.v1.EnrollmentStatus" json:"status,omitempty"`
	BiscuitToken          []byte                 `protobuf:"bytes,2,opt,name=biscuit_token,json=biscuitToken,proto3" json:"biscuit_token,omitempty"`                         // Populated only if APPROVED
	PollIntervalSeconds   int32                  `protobuf:"varint,3,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"` // Recommended polling wait time
	ErrorMessage          string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ControlPlanePublicKey []byte                 `protobuf:"bytes,5,opt,name=control_plane_public_key,json=controlPlanePublicKey,proto3" json:"control_plane_public_key,omitempty"` // Populated only if APPROVED
	RouterAddresses       []string               `protobuf:"bytes,6,rep,name=router_addresses,json=routerAddresses,proto3" json:"router_addresses,omitempty"`                       // Populated only if APPROVED
	Expiration            int64                  `protobuf:"varint,7,opt,name=expiration,proto3" json:"expiration,omitempty"`                                                       // Populated only if APPROVED
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BootstrapEnrollResponse) Reset() {
	*x = BootstrapEnrollResponse{}
	mi := &file_api_sam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapEnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapEnrollResponse) ProtoMessage() {}

func (x *BootstrapEnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapEnrollResponse.ProtoReflect.Descriptor instead.
func (*BootstrapEnrollResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{6}
}

func (x *BootstrapEnrollResponse) GetStatus() EnrollmentStatus {
	if x != nil {
		return x.Status
	}
	return EnrollmentStatus_ENROLLMENT_STATUS_UNSPECIFIED
}

func (x *BootstrapEnrollResponse) GetBiscuitToken() []byte {
	if x != nil {
		return x.BiscuitToken
	}
	return nil
}

func (x *BootstrapEnrollResponse) GetPollIntervalSeconds() int32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

func (x *BootstrapEnrollResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BootstrapEnrollResponse) GetControlPlanePublicKey() []byte {
	if x != nil {
		return x.ControlPlanePublicKey
	}
	return nil
}

func (x *BootstrapEnrollResponse) GetRouterAddresses() []string {
	if x != nil {
		return x.RouterAddresses
	}
	return nil
}

func (x *BootstrapEnrollResponse) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ServiceType            `protobuf:"varint,1,opt,name=type,proto3,enum=sam.v1.ServiceType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_api_sam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceInfo) GetType() ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CommandBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandBackend) Reset() {
	*x = CommandBackend{}
	mi := &file_api_sam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandBackend) ProtoMessage() {}

func (x *CommandBackend) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandBackend.ProtoReflect.Descriptor instead.
func (*CommandBackend) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{8}
}

func (x *CommandBackend) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandBackend) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type RegisterServiceRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Service *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Types that are valid to be assigned to Backend:
	//
	//	*RegisterServiceRequest_TargetUrl
	//	*RegisterServiceRequest_Command
	Backend       isRegisterServiceRequest_Backend `protobuf_oneof:"backend"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_api_sam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterServiceRequest) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *RegisterServiceRequest) GetBackend() isRegisterServiceRequest_Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *RegisterServiceRequest) GetTargetUrl() string {
	if x != nil {
		if x, ok := x.Backend.(*RegisterServiceRequest_TargetUrl); ok {
			return x.TargetUrl
		}
	}
	return ""
}

func (x *RegisterServiceRequest) GetCommand() *CommandBackend {
	if x != nil {
		if x, ok := x.Backend.(*RegisterServiceRequest_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isRegisterServiceRequest_Backend interface {
	isRegisterServiceRequest_Backend()
}

type RegisterServiceRequest_TargetUrl struct {
	TargetUrl string `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3,oneof"`
}

type RegisterServiceRequest_Command struct {
	Command *CommandBackend `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

func (*RegisterServiceRequest_TargetUrl) isRegisterServiceRequest_Backend() {}

func (*RegisterServiceRequest_Command) isRegisterServiceRequest_Backend() {}

type DiscoveredProvider struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeerId         string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	LocalProxyUrl  string                 `protobuf:"bytes,2,opt,name=local_proxy_url,json=localProxyUrl,proto3" json:"local_proxy_url,omitempty"`
	SrvName        string                 `protobuf:"bytes,3,opt,name=srv_name,json=srvName,proto3" json:"srv_name,omitempty"`
	SrvDescription string                 `protobuf:"bytes,4,opt,name=srv_description,json=srvDescription,proto3" json:"srv_description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiscoveredProvider) Reset() {
	*x = DiscoveredProvider{}
	mi := &file_api_sam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredProvider) ProtoMessage() {}

func (x *DiscoveredProvider) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredProvider.ProtoReflect.Descriptor instead.
func (*DiscoveredProvider) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{10}
}

func (x *DiscoveredProvider) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *DiscoveredProvider) GetLocalProxyUrl() string {
	if x != nil {
		return x.LocalProxyUrl
	}
	return ""
}

func (x *DiscoveredProvider) GetSrvName() string {
	if x != nil {
		return x.SrvName
	}
	return ""
}

func (x *DiscoveredProvider) GetSrvDescription() string {
	if x != nil {
		return x.SrvDescription
	}
	return ""
}

// ServiceAnnounce is gossiped by a node on per-key topics (see
// DiscoveryTopic) while those topics have subscribers. It is a routing
// hint signed at the pubsub layer by the announcing peer: consumers use
// it for freshness and load awareness, never for authorization.
type ServiceAnnounce struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PeerId      string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Type        ServiceType            `protobuf:"varint,2,opt,name=type,proto3,enum=sam.v1.ServiceType" json:"type,omitempty"`
	ServiceName string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Routing keys served by this service: model IDs for inference,
	// tool names for MCP.
	Keys []string `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	// Operator-declared labels (e.g. "region"). Operator claims always
	// take precedence over runtime-derived values.
	Labels map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Runtime load hints; zero values mean unknown.
	ActiveRequests uint32  `protobuf:"varint,6,opt,name=active_requests,json=activeRequests,proto3" json:"active_requests,omitempty"`
	LatencyEwmaMs  float64 `protobuf:"fixed64,7,opt,name=latency_ewma_ms,json=latencyEwmaMs,proto3" json:"latency_ewma_ms,omitempty"`
	Timestamp      int64   `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceAnnounce) Reset() {
	*x = ServiceAnnounce{}
	mi := &file_api_sam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAnnounce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAnnounce) ProtoMessage() {}

func (x *ServiceAnnounce) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAnnounce.ProtoReflect.Descriptor instead.
func (*ServiceAnnounce) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceAnnounce) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ServiceAnnounce) GetType() ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *ServiceAnnounce) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceAnnounce) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ServiceAnnounce) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ServiceAnnounce) GetActiveRequests() uint32 {
	if x != nil {
		return x.ActiveRequests
	}
	return 0
}

func (x *ServiceAnnounce) GetLatencyEwmaMs() float64 {
	if x != nil {
		return x.LatencyEwmaMs
	}
	return 0
}

func (x *ServiceAnnounce) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ControlPlaneInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OidcIssuer      string                 `protobuf:"bytes,1,opt,name=oidc_issuer,json=oidcIssuer,proto3" json:"oidc_issuer,omitempty"`
	ClientId        string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Audience        string                 `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	RouterAddresses []string               `protobuf:"bytes,4,rep,name=router_addresses,json=routerAddresses,proto3" json:"router_addresses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ControlPlaneInfoResponse) Reset() {
	*x = ControlPlaneInfoResponse{}
	mi := &file_api_sam_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlaneInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlaneInfoResponse) ProtoMessage() {}

func (x *ControlPlaneInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlaneInfoResponse.ProtoReflect.Descriptor instead.
func (*ControlPlaneInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{12}
}

func (x *ControlPlaneInfoResponse) GetOidcIssuer() string {
	if x != nil {
		return x.OidcIssuer
	}
	return ""
}

func (x *ControlPlaneInfoResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ControlPlaneInfoResponse) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *ControlPlaneInfoResponse) GetRouterAddresses() []string {
	if x != nil {
		return x.RouterAddresses
	}
	return nil
}

type RouterLeaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeerId         string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addresses      []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Biscuit        []byte                 `protobuf:"bytes,3,opt,name=biscuit,proto3" json:"biscuit,omitempty"`
	ConnectedPeers []string               `protobuf:"bytes,4,rep,name=connected_peers,json=connectedPeers,proto3" json:"connected_peers,omitempty"`
	DhtSize        int32                  `protobuf:"varint,5,opt,name=dht_size,json=dhtSize,proto3" json:"dht_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouterLeaseRequest) Reset() {
	*x = RouterLeaseRequest{}
	mi := &file_api_sam_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterLeaseRequest) ProtoMessage() {}

func (x *RouterLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterLeaseRequest.ProtoReflect.Descriptor instead.
func (*RouterLeaseRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{13}
}

func (x *RouterLeaseRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *RouterLeaseRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *RouterLeaseRequest) GetBiscuit() []byte {
	if x != nil {
		return x.Biscuit
	}
	return nil
}

func (x *RouterLeaseRequest) GetConnectedPeers() []string {
	if x != nil {
		return x.ConnectedPeers
	}
	return nil
}

func (x *RouterLeaseRequest) GetDhtSize() int32 {
	if x != nil {
		return x.DhtSize
	}
	return 0
}

type RouterLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterLeaseResponse) Reset() {
	*x = RouterLeaseResponse{}
	mi := &file_api_sam_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterLeaseResponse) ProtoMessage() {}

func (x *RouterLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterLeaseResponse.ProtoReflect.Descriptor instead.
func (*RouterLeaseResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{14}
}

func (x *RouterLeaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RouterLeaseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RouterLeaseResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type PolicyRole struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AllowedTargets  []string               `protobuf:"bytes,2,rep,name=allowed_targets,json=allowedTargets,proto3" json:"allowed_targets,omitempty"`
	AllowedServices []string               `protobuf:"bytes,3,rep,name=allowed_services,json=allowedServices,proto3" json:"allowed_services,omitempty"`
	CustomDatalog   []string               `protobuf:"bytes,4,rep,name=custom_datalog,json=customDatalog,proto3" json:"custom_datalog,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PolicyRole) Reset() {
	*x = PolicyRole{}
	mi := &file_api_sam_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRole) ProtoMessage() {}

func (x *PolicyRole) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRole.ProtoReflect.Descriptor instead.
func (*PolicyRole) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{15}
}

func (x *PolicyRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyRole) GetAllowedTargets() []string {
	if x != nil {
		return x.AllowedTargets
	}
	return nil
}

func (x *PolicyRole) GetAllowedServices() []string {
	if x != nil {
		return x.AllowedServices
	}
	return nil
}

func (x *PolicyRole) GetCustomDatalog() []string {
	if x != nil {
		return x.CustomDatalog
	}
	return nil
}

type PolicyBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Members       []string               `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyBinding) Reset() {
	*x = PolicyBinding{}
	mi := &file_api_sam_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBinding) ProtoMessage() {}

func (x *PolicyBinding) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBinding.ProtoReflect.Descriptor instead.
func (*PolicyBinding) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{16}
}

func (x *PolicyBinding) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PolicyBinding) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type PolicyConfigGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyConfigGetRequest) Reset() {
	*x = PolicyConfigGetRequest{}
	mi := &file_api_sam_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyConfigGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyConfigGetRequest) ProtoMessage() {}

func (x *PolicyConfigGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyConfigGetRequest.ProtoReflect.Descriptor instead.
func (*PolicyConfigGetRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{17}
}

type PolicyConfigGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*PolicyRole          `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Bindings      []*PolicyBinding       `protobuf:"bytes,2,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyConfigGetResponse) Reset() {
	*x = PolicyConfigGetResponse{}
	mi := &file_api_sam_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyConfigGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyConfigGetResponse) ProtoMessage() {}

func (x *PolicyConfigGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyConfigGetResponse.ProtoReflect.Descriptor instead.
func (*PolicyConfigGetResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{18}
}

func (x *PolicyConfigGetResponse) GetRoles() []*PolicyRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *PolicyConfigGetResponse) GetBindings() []*PolicyBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type PolicyConfigUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*PolicyRole          `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Bindings      []*PolicyBinding       `protobuf:"bytes,2,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyConfigUpdateRequest) Reset() {
	*x = PolicyConfigUpdateRequest{}
	mi := &file_api_sam_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyConfigUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyConfigUpdateRequest) ProtoMessage() {}

func (x *PolicyConfigUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyConfigUpdateRequest.ProtoReflect.Descriptor instead.
func (*PolicyConfigUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{19}
}

func (x *PolicyConfigUpdateRequest) GetRoles() []*PolicyRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *PolicyConfigUpdateRequest) GetBindings() []*PolicyBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type PolicyConfigUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyConfigUpdateResponse) Reset() {
	*x = PolicyConfigUpdateResponse{}
	mi := &file_api_sam_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyConfigUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyConfigUpdateResponse) ProtoMessage() {}

func (x *PolicyConfigUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyConfigUpdateResponse.ProtoReflect.Descriptor instead.
func (*PolicyConfigUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{20}
}

func (x *PolicyConfigUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PolicyConfigUpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKeys    [][]byte               `protobuf:"bytes,1,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysResponse) Reset() {
	*x = KeysResponse{}
	mi := &file_api_sam_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysResponse) ProtoMessage() {}

func (x *KeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysResponse.ProtoReflect.Descriptor instead.
func (*KeysResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{21}
}

func (x *KeysResponse) GetPublicKeys() [][]byte {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type TokenRefreshRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChallengeSignature []byte                 `protobuf:"bytes,1,opt,name=challenge_signature,json=challengeSignature,proto3" json:"challenge_signature,omitempty"`
	Timestamp          int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TokenRefreshRequest) Reset() {
	*x = TokenRefreshRequest{}
	mi := &file_api_sam_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRefreshRequest) ProtoMessage() {}

func (x *TokenRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRefreshRequest.ProtoReflect.Descriptor instead.
func (*TokenRefreshRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{22}
}

func (x *TokenRefreshRequest) GetChallengeSignature() []byte {
	if x != nil {
		return x.ChallengeSignature
	}
	return nil
}

func (x *TokenRefreshRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TokenRefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BiscuitToken  []byte                 `protobuf:"bytes,1,opt,name=biscuit_token,json=biscuitToken,proto3" json:"biscuit_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRefreshResponse) Reset() {
	*x = TokenRefreshResponse{}
	mi := &file_api_sam_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRefreshResponse) ProtoMessage() {}

func (x *TokenRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRefreshResponse.ProtoReflect.Descriptor instead.
func (*TokenRefreshResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{23}
}

func (x *TokenRefreshResponse) GetBiscuitToken() []byte {
	if x != nil {
		return x.BiscuitToken
	}
	return nil
}

func (x *TokenRefreshResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *TokenRefreshResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type TokenRevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRevokeRequest) Reset() {
	*x = TokenRevokeRequest{}
	mi := &file_api_sam_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRevokeRequest) ProtoMessage() {}

func (x *TokenRevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRevokeRequest.ProtoReflect.Descriptor instead.
func (*TokenRevokeRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{24}
}

func (x *TokenRevokeRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type TokenRevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRevokeResponse) Reset() {
	*x = TokenRevokeResponse{}
	mi := &file_api_sam_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRevokeResponse) ProtoMessage() {}

func (x *TokenRevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRevokeResponse.ProtoReflect.Descriptor instead.
func (*TokenRevokeResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{25}
}

func (x *TokenRevokeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TokenRevokeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AgentSecret configures credential injection for one destination. It carries
// a path, never a value: secret material must not travel through this API.
type AgentSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                               // bearer | basicauth | customheader
	HeaderName    string                 `protobuf:"bytes,3,opt,name=header_name,json=headerName,proto3" json:"header_name,omitempty"` // customheader only
	ValuePath     string                 `protobuf:"bytes,4,opt,name=value_path,json=valuePath,proto3" json:"value_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSecret) Reset() {
	*x = AgentSecret{}
	mi := &file_api_sam_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSecret) ProtoMessage() {}

func (x *AgentSecret) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSecret.ProtoReflect.Descriptor instead.
func (*AgentSecret) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{26}
}

func (x *AgentSecret) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AgentSecret) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AgentSecret) GetHeaderName() string {
	if x != nil {
		return x.HeaderName
	}
	return ""
}

func (x *AgentSecret) GetValuePath() string {
	if x != nil {
		return x.ValuePath
	}
	return ""
}

// AgentEgress is deny-by-default. Patterns are matched against the destination
// name taken from the sandbox boundary, never against a resolved address.
type AgentEgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         []string               `protobuf:"bytes,1,rep,name=allow,proto3" json:"allow,omitempty"`
	Secrets       []*AgentSecret         `protobuf:"bytes,2,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEgress) Reset() {
	*x = AgentEgress{}
	mi := &file_api_sam_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEgress) ProtoMessage() {}

func (x *AgentEgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEgress.ProtoReflect.Descriptor instead.
func (*AgentEgress) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{27}
}

func (x *AgentEgress) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

func (x *AgentEgress) GetSecrets() []*AgentSecret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// AgentIngress declares that the agent serves a mesh service. The name is the
// service half of the mesh host the rest of the mesh dials (see api/names.go);
// port is where the agent listens inside its sandbox.
type AgentIngress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ServiceType            `protobuf:"varint,1,opt,name=type,proto3,enum=sam.v1.ServiceType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentIngress) Reset() {
	*x = AgentIngress{}
	mi := &file_api_sam_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIngress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIngress) ProtoMessage() {}

func (x *AgentIngress) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIngress.ProtoReflect.Descriptor instead.
func (*AgentIngress) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{28}
}

func (x *AgentIngress) GetType() ServiceType {
	if x != nil {
		return x.Type
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *AgentIngress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentIngress) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AgentIngress) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// AgentBundle is everything the platform declares about one agent. Its
// canonical form is a YAML file in the agent's own state directory, so that a
// suspend/resume onto another host carries it with no extra machinery; this
// message is the transport mirror of that file.
type AgentBundle struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Canonical mesh identifier, without the "agent:" prefix. Dot-separated and
	// DNS-shaped; see api/agent.go for the rules and why they exist.
	AgentId string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The platform's own identifier, verbatim, kept for audit because the
	// translation into agent_id is not always reversible.
	ExternalId string `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// Path to the workload credential the platform already issues: a projected
	// Kubernetes service-account token, a pod certificate, or an SVID. It is
	// verified at admission against the platform's issuer and then translated
	// into agent facts, the same way OIDC claims are translated at node
	// enrollment. The scheduler needs no mesh credential of its own.
	CredentialPath string          `protobuf:"bytes,4,opt,name=credential_path,json=credentialPath,proto3" json:"credential_path,omitempty"`
	Egress         *AgentEgress    `protobuf:"bytes,5,opt,name=egress,proto3" json:"egress,omitempty"`
	Ingress        []*AgentIngress `protobuf:"bytes,6,rep,name=ingress,proto3" json:"ingress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentBundle) Reset() {
	*x = AgentBundle{}
	mi := &file_api_sam_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentBundle) ProtoMessage() {}

func (x *AgentBundle) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentBundle.ProtoReflect.Descriptor instead.
func (*AgentBundle) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{29}
}

func (x *AgentBundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentBundle) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentBundle) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *AgentBundle) GetCredentialPath() string {
	if x != nil {
		return x.CredentialPath
	}
	return ""
}

func (x *AgentBundle) GetEgress() *AgentEgress {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *AgentBundle) GetIngress() []*AgentIngress {
	if x != nil {
		return x.Ingress
	}
	return nil
}

// AgentAttachRequest admits an agent. It is idempotent on agent_id: resuming
// after a crash or a migration is another Attach, not a distinct operation.
type AgentAttachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundle        *AgentBundle           `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAttachRequest) Reset() {
	*x = AgentAttachRequest{}
	mi := &file_api_sam_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAttachRequest) ProtoMessage() {}

func (x *AgentAttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAttachRequest.ProtoReflect.Descriptor instead.
func (*AgentAttachRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{30}
}

func (x *AgentAttachRequest) GetBundle() *AgentBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

type AgentAttachResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sandbox boundary endpoints to wire into the sandbox: SOCKS5 for guest to
	// host, and a reverse channel for host to guest that is empty when the
	// bundle declares no ingress.
	EgressSocket  string `protobuf:"bytes,1,opt,name=egress_socket,json=egressSocket,proto3" json:"egress_socket,omitempty"`
	IngressSocket string `protobuf:"bytes,2,opt,name=ingress_socket,json=ingressSocket,proto3" json:"ingress_socket,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAttachResponse) Reset() {
	*x = AgentAttachResponse{}
	mi := &file_api_sam_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAttachResponse) ProtoMessage() {}

func (x *AgentAttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAttachResponse.ProtoReflect.Descriptor instead.
func (*AgentAttachResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{31}
}

func (x *AgentAttachResponse) GetEgressSocket() string {
	if x != nil {
		return x.EgressSocket
	}
	return ""
}

func (x *AgentAttachResponse) GetIngressSocket() string {
	if x != nil {
		return x.IngressSocket
	}
	return ""
}

func (x *AgentAttachResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AgentDetachRequest stops an agent: ingress is unregistered, channels are
// closed and credentials dropped. It must leave no residual advertisement.
type AgentDetachRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDetachRequest) Reset() {
	*x = AgentDetachRequest{}
	mi := &file_api_sam_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDetachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDetachRequest) ProtoMessage() {}

func (x *AgentDetachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDetachRequest.ProtoReflect.Descriptor instead.
func (*AgentDetachRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{32}
}

func (x *AgentDetachRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AgentDetachResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDetachResponse) Reset() {
	*x = AgentDetachResponse{}
	mi := &file_api_sam_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDetachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDetachResponse) ProtoMessage() {}

func (x *AgentDetachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDetachResponse.ProtoReflect.Descriptor instead.
func (*AgentDetachResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{33}
}

func (x *AgentDetachResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentDetachResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AgentRefreshRequest hands in a rotated workload credential. Platforms rotate
// these on their own schedule, which is what bounds how long a stale admission
// stays usable.
type AgentRefreshRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CredentialPath string                 `protobuf:"bytes,2,opt,name=credential_path,json=credentialPath,proto3" json:"credential_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentRefreshRequest) Reset() {
	*x = AgentRefreshRequest{}
	mi := &file_api_sam_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRefreshRequest) ProtoMessage() {}

func (x *AgentRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRefreshRequest.ProtoReflect.Descriptor instead.
func (*AgentRefreshRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{34}
}

func (x *AgentRefreshRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRefreshRequest) GetCredentialPath() string {
	if x != nil {
		return x.CredentialPath
	}
	return ""
}

type AgentRefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRefreshResponse) Reset() {
	*x = AgentRefreshResponse{}
	mi := &file_api_sam_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRefreshResponse) ProtoMessage() {}

func (x *AgentRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRefreshResponse.ProtoReflect.Descriptor instead.
func (*AgentRefreshResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{35}
}

func (x *AgentRefreshResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentRefreshResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentRefreshResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// AgentStatusRequest reports on one agent, or on all of them when agent_id is
// empty, for a scheduler's reconcile loop.
type AgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusRequest) Reset() {
	*x = AgentStatusRequest{}
	mi := &file_api_sam_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusRequest) ProtoMessage() {}

func (x *AgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusRequest.ProtoReflect.Descriptor instead.
func (*AgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{36}
}

func (x *AgentStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AgentStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentId             string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Attached            bool                   `protobuf:"varint,2,opt,name=attached,proto3" json:"attached,omitempty"`
	Ingress             []*AgentIngress        `protobuf:"bytes,3,rep,name=ingress,proto3" json:"ingress,omitempty"`
	CredentialExpiresAt int64                  `protobuf:"varint,4,opt,name=credential_expires_at,json=credentialExpiresAt,proto3" json:"credential_expires_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_api_sam_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{37}
}

func (x *AgentStatus) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStatus) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

func (x *AgentStatus) GetIngress() []*AgentIngress {
	if x != nil {
		return x.Ingress
	}
	return nil
}

func (x *AgentStatus) GetCredentialExpiresAt() int64 {
	if x != nil {
		return x.CredentialExpiresAt
	}
	return 0
}

type AgentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentStatus         `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusResponse) Reset() {
	*x = AgentStatusResponse{}
	mi := &file_api_sam_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusResponse) ProtoMessage() {}

func (x *AgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusResponse.ProtoReflect.Descriptor instead.
func (*AgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{38}
}

func (x *AgentStatusResponse) GetAgents() []*AgentStatus {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *AgentStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IdentityEvidenceResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	PeerId                  string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Biscuit                 []byte                 `protobuf:"bytes,2,opt,name=biscuit,proto3" json:"biscuit,omitempty"`
	BiscuitExpiresAt        int64                  `protobuf:"varint,3,opt,name=biscuit_expires_at,json=biscuitExpiresAt,proto3" json:"biscuit_expires_at,omitempty"`
	ControlPlaneUrl         string                 `protobuf:"bytes,4,opt,name=control_plane_url,json=controlPlaneUrl,proto3" json:"control_plane_url,omitempty"`
	TrustedControlPlaneKeys [][]byte               `protobuf:"bytes,5,rep,name=trusted_control_plane_keys,json=trustedControlPlaneKeys,proto3" json:"trusted_control_plane_keys,omitempty"` // Ed25519 SPKI DER
	CheckedAt               int64                  `protobuf:"varint,6,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *IdentityEvidenceResponse) Reset() {
	*x = IdentityEvidenceResponse{}
	mi := &file_api_sam_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityEvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityEvidenceResponse) ProtoMessage() {}

func (x *IdentityEvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityEvidenceResponse.ProtoReflect.Descriptor instead.
func (*IdentityEvidenceResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{39}
}

func (x *IdentityEvidenceResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *IdentityEvidenceResponse) GetBiscuit() []byte {
	if x != nil {
		return x.Biscuit
	}
	return nil
}

func (x *IdentityEvidenceResponse) GetBiscuitExpiresAt() int64 {
	if x != nil {
		return x.BiscuitExpiresAt
	}
	return 0
}

func (x *IdentityEvidenceResponse) GetControlPlaneUrl() string {
	if x != nil {
		return x.ControlPlaneUrl
	}
	return ""
}

func (x *IdentityEvidenceResponse) GetTrustedControlPlaneKeys() [][]byte {
	if x != nil {
		return x.TrustedControlPlaneKeys
	}
	return nil
}

func (x *IdentityEvidenceResponse) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

type PeerEvidenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Biscuit       []byte                 `protobuf:"bytes,2,opt,name=biscuit,proto3" json:"biscuit,omitempty"`
	VerifyingKey  []byte                 `protobuf:"bytes,3,opt,name=verifying_key,json=verifyingKey,proto3" json:"verifying_key,omitempty"` // Ed25519 SPKI DER, member of the trusted set
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Expiration    int64                  `protobuf:"varint,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	RevocationIds []string               `protobuf:"bytes,7,rep,name=revocation_ids,json=revocationIds,proto3" json:"revocation_ids,omitempty"` // hex
	CheckedAt     int64                  `protobuf:"varint,8,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerEvidenceResponse) Reset() {
	*x = PeerEvidenceResponse{}
	mi := &file_api_sam_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerEvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerEvidenceResponse) ProtoMessage() {}

func (x *PeerEvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sam_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerEvidenceResponse.ProtoReflect.Descriptor instead.
func (*PeerEvidenceResponse) Descriptor() ([]byte, []int) {
	return file_api_sam_proto_rawDescGZIP(), []int{40}
}

func (x *PeerEvidenceResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerEvidenceResponse) GetBiscuit() []byte {
	if x != nil {
		return x.Biscuit
	}
	return nil
}

func (x *PeerEvidenceResponse) GetVerifyingKey() []byte {
	if x != nil {
		return x.VerifyingKey
	}
	return nil
}

func (x *PeerEvidenceResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *PeerEvidenceResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PeerEvidenceResponse) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

func (x *PeerEvidenceResponse) GetRevocationIds() []string {
	if x != nil {
		return x.RevocationIds
	}
	return nil
}

func (x *PeerEvidenceResponse) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

var File_api_sam_proto protoreflect.FileDescriptor

const file_api_sam_proto_rawDesc = "" +
	"\n" +
	"\rapi/sam.proto\x12\x06sam.v1\"b\n" +
	"\tAuthFrame\x12\x18\n" +
	"\abiscuit\x18\x01 \x01(\fR\abiscuit\x12%\n" +
	"\x0etarget_service\x18\x02 \x01(\tR\rtargetService\x12\x14\n" +
	"\x05agent\x18\x03 \x01(\tR\x05agent\"X\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\abiscuit\x18\x03 \x01(\fR\abiscuit\"\xeb\x01\n" +
	"\tMeshEvent\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.sam.v1.MeshEvent.TypeR\x04type\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12$\n" +
	"\x0enew_public_key\x18\x04 \x01(\fR\fnewPublicKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"7\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06BANNED\x10\x00\x12\x10\n" +
	"\fKEY_ROTATION\x10\x01\x12\x11\n" +
	"\rPOLICY_UPDATE\x10\x02\"\xf6\x01\n" +
	"\rEnrollRequest\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12%\n" +
	"\x0erequested_role\x18\x04 \x01(\tR\rrequestedRole\x129\n" +
	"\x06labels\x18\x05 \x03(\v2!.sam.v1.EnrollRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x01\n" +
	"\x0eEnrollResponse\x12#\n" +
	"\rbiscuit_token\x18\x01 \x01(\fR\fbiscuitToken\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x127\n" +
	"\x18control_plane_public_key\x18\x03 \x01(\fR\x15controlPlanePublicKey\x12)\n" +
	"\x10router_addresses\x18\x04 \x03(\tR\x0frouterAddresses\x12\x1e\n" +
	"\n" +
	"expiration\x18\x05 \x01(\x03R\n" +
	"expiration\"\x9f\x02\n" +
	"\x16BootstrapEnrollRequest\x12'\n" +
	"\x0fbootstrap_token\x18\x01 \x01(\tR\x0ebootstrapToken\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12%\n" +
	"\x0erequested_role\x18\x04 \x01(\tR\rrequestedRole\x12B\n" +
	"\x06labels\x18\x05 \x03(\v2*.sam.v1.BootstrapEnrollRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x02\n" +
	"\x17BootstrapEnrollResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.sam.v1.EnrollmentStatusR\x06status\x12#\n" +
	"\rbiscuit_token\x18\x02 \x01(\fR\fbiscuitToken\x122\n" +
	"\x15poll_interval_seconds\x18\x03 \x01(\x05R\x13pollIntervalSeconds\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x127\n" +
	"\x18control_plane_public_key\x18\x05 \x01(\fR\x15controlPlanePublicKey\x12)\n" +
	"\x10router_addresses\x18\x06 \x03(\tR\x0frouterAddresses\x12\x1e\n" +
	"\n" +
	"expiration\x18\a \x01(\x03R\n" +
	"expiration\"l\n" +
	"\vServiceInfo\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.sam.v1.ServiceTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x95\x01\n" +
	"\x0eCommandBackend\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x121\n" +
	"\x03env\x18\x02 \x03(\v2\x1f.sam.v1.CommandBackend.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\x16RegisterServiceRequest\x12-\n" +
	"\aservice\x18\x01 \x01(\v2\x13.sam.v1.ServiceInfoR\aservice\x12\x1f\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tH\x00R\ttargetUrl\x122\n" +
	"\acommand\x18\x03 \x01(\v2\x16.sam.v1.CommandBackendH\x00R\acommandB\t\n" +
	"\abackend\"\x99\x01\n" +
	"\x12DiscoveredProvider\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12&\n" +
	"\x0flocal_proxy_url\x18\x02 \x01(\tR\rlocalProxyUrl\x12\x19\n" +
	"\bsrv_name\x18\x03 \x01(\tR\asrvName\x12'\n" +
	"\x0fsrv_description\x18\x04 \x01(\tR\x0esrvDescription\"\xf1\x02\n" +
	"\x0fServiceAnnounce\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.sam.v1.ServiceTypeR\x04type\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04keys\x18\x04 \x03(\tR\x04keys\x12;\n" +
	"\x06labels\x18\x05 \x03(\v2#.sam.v1.ServiceAnnounce.LabelsEntryR\x06labels\x12'\n" +
	"\x0factive_requests\x18\x06 \x01(\rR\x0eactiveRequests\x12&\n" +
	"\x0flatency_ewma_ms\x18\a \x01(\x01R\rlatencyEwmaMs\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x18ControlPlaneInfoResponse\x12\x1f\n" +
	"\voidc_issuer\x18\x01 \x01(\tR\n" +
	"oidcIssuer\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1a\n" +
	"\baudience\x18\x03 \x01(\tR\baudience\x12)\n" +
	"\x10router_addresses\x18\x04 \x03(\tR\x0frouterAddresses\"\xa9\x01\n" +
	"\x12RouterLeaseRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x18\n" +
	"\abiscuit\x18\x03 \x01(\fR\abiscuit\x12'\n" +
	"\x0fconnected_peers\x18\x04 \x03(\tR\x0econnectedPeers\x12\x19\n" +
	"\bdht_size\x18\x05 \x01(\x05R\adhtSize\"d\n" +
	"\x13RouterLeaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"\x9b\x01\n" +
	"\n" +
	"PolicyRole\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fallowed_targets\x18\x02 \x03(\tR\x0eallowedTargets\x12)\n" +
	"\x10allowed_services\x18\x03 \x03(\tR\x0fallowedServices\x12%\n" +
	"\x0ecustom_datalog\x18\x04 \x03(\tR\rcustomDatalog\"=\n" +
	"\rPolicyBinding\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\"\x18\n" +
	"\x16PolicyConfigGetRequest\"v\n" +
	"\x17PolicyConfigGetResponse\x12(\n" +
	"\x05roles\x18\x01 \x03(\v2\x12.sam.v1.PolicyRoleR\x05roles\x121\n" +
	"\bbindings\x18\x02 \x03(\v2\x15.sam.v1.PolicyBindingR\bbindings\"x\n" +
	"\x19PolicyConfigUpdateRequest\x12(\n" +
	"\x05roles\x18\x01 \x03(\v2\x12.sam.v1.PolicyRoleR\x05roles\x121\n" +
	"\bbindings\x18\x02 \x03(\v2\x15.sam.v1.PolicyBindingR\bbindings\"L\n" +
	"\x1aPolicyConfigUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"/\n" +
	"\fKeysResponse\x12\x1f\n" +
	"\vpublic_keys\x18\x01 \x03(\fR\n" +
	"publicKeys\"d\n" +
	"\x13TokenRefreshRequest\x12/\n" +
	"\x13challenge_signature\x18\x01 \x01(\fR\x12challengeSignature\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x7f\n" +
	"\x14TokenRefreshResponse\x12#\n" +
	"\rbiscuit_token\x18\x01 \x01(\fR\fbiscuitToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"-\n" +
	"\x12TokenRevokeRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"E\n" +
	"\x13TokenRevokeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"u\n" +
	"\vAgentSecret\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1f\n" +
	"\vheader_name\x18\x03 \x01(\tR\n" +
	"headerName\x12\x1d\n" +
	"\n" +
	"value_path\x18\x04 \x01(\tR\tvaluePath\"R\n" +
	"\vAgentEgress\x12\x14\n" +
	"\x05allow\x18\x01 \x03(\tR\x05allow\x12-\n" +
	"\asecrets\x18\x02 \x03(\v2\x13.sam.v1.AgentSecretR\asecrets\"\x81\x01\n" +
	"\fAgentIngress\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.sam.v1.ServiceTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xe9\x01\n" +
	"\vAgentBundle\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12'\n" +
	"\x0fcredential_path\x18\x04 \x01(\tR\x0ecredentialPath\x12+\n" +
	"\x06egress\x18\x05 \x01(\v2\x13.sam.v1.AgentEgressR\x06egress\x12.\n" +
	"\aingress\x18\x06 \x03(\v2\x14.sam.v1.AgentIngressR\aingress\"A\n" +
	"\x12AgentAttachRequest\x12+\n" +
	"\x06bundle\x18\x01 \x01(\v2\x13.sam.v1.AgentBundleR\x06bundle\"w\n" +
	"\x13AgentAttachResponse\x12#\n" +
	"\regress_socket\x18\x01 \x01(\tR\fegressSocket\x12%\n" +
	"\x0eingress_socket\x18\x02 \x01(\tR\ringressSocket\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"/\n" +
	"\x12AgentDetachRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"E\n" +
	"\x13AgentDetachResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Y\n" +
	"\x13AgentRefreshRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0fcredential_path\x18\x02 \x01(\tR\x0ecredentialPath\"e\n" +
	"\x14AgentRefreshResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"/\n" +
	"\x12AgentStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xa8\x01\n" +
	"\vAgentStatus\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\battached\x18\x02 \x01(\bR\battached\x12.\n" +
	"\aingress\x18\x03 \x03(\v2\x14.sam.v1.AgentIngressR\aingress\x122\n" +
	"\x15credential_expires_at\x18\x04 \x01(\x03R\x13credentialExpiresAt\"X\n" +
	"\x13AgentStatusResponse\x12+\n" +
	"\x06agents\x18\x01 \x03(\v2\x13.sam.v1.AgentStatusR\x06agents\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x83\x02\n" +
	"\x18IdentityEvidenceResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\abiscuit\x18\x02 \x01(\fR\abiscuit\x12,\n" +
	"\x12biscuit_expires_at\x18\x03 \x01(\x03R\x10biscuitExpiresAt\x12*\n" +
	"\x11control_plane_url\x18\x04 \x01(\tR\x0fcontrolPlaneUrl\x12;\n" +
	"\x1atrusted_control_plane_keys\x18\x05 \x03(\fR\x17trustedControlPlaneKeys\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x06 \x01(\x03R\tcheckedAt\"\xe7\x02\n" +
	"\x14PeerEvidenceResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x18\n" +
	"\abiscuit\x18\x02 \x01(\fR\abiscuit\x12#\n" +
	"\rverifying_key\x18\x03 \x01(\fR\fverifyingKey\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12@\n" +
	"\x06labels\x18\x05 \x03(\v2(.sam.v1.PeerEvidenceResponse.LabelsEntryR\x06labels\x12\x1e\n" +
	"\n" +
	"expiration\x18\x06 \x01(\x03R\n" +
	"expiration\x12%\n" +
	"\x0erevocation_ids\x18\a \x03(\tR\rrevocationIds\x12\x1d\n" +
	"\n" +
	"checked_at\x18\b \x01(\x03R\tcheckedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x94\x01\n" +
	"\x10EnrollmentStatus\x12!\n" +
	"\x1dENROLLMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ENROLLMENT_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aENROLLMENT_STATUS_APPROVED\x10\x02\x12\x1e\n" +
	"\x1aENROLLMENT_STATUS_REJECTED\x10\x03*]\n" +
	"\vServiceType\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SERVICE_TYPE_MCP\x10\x01\x12\x1a\n" +
	"\x16SERVICE_TYPE_INFERENCE\x10\x02B\x1bZ\x19github.com/google/sam/apib\x06proto3"

var (
	file_api_sam_proto_rawDescOnce sync.Once
	file_api_sam_proto_rawDescData []byte
)

func file_api_sam_proto_rawDescGZIP() []byte {
	file_api_sam_proto_rawDescOnce.Do(func() {
		file_api_sam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_sam_proto_rawDesc), len(file_api_sam_proto_rawDesc)))
	})
	return file_api_sam_proto_rawDescData
}

var file_api_sam_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_sam_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_api_sam_proto_goTypes = []any{
	(EnrollmentStatus)(0),              // 0: sam.v1.EnrollmentStatus
	(ServiceType)(0),                   // 1: sam.v1.ServiceType
	(MeshEvent_Type)(0),                // 2: sam.v1.MeshEvent.Type
	(*AuthFrame)(nil),                  // 3: sam.v1.AuthFrame
	(*AuthResponse)(nil),               // 4: sam.v1.AuthResponse
	(*MeshEvent)(nil),                  // 5: sam.v1.MeshEvent
	(*EnrollRequest)(nil),              // 6: sam.v1.EnrollRequest
	(*EnrollResponse)(nil),             // 7: sam.v1.EnrollResponse
	(*BootstrapEnrollRequest)(nil),     // 8: sam.v1.BootstrapEnrollRequest
	(*BootstrapEnrollResponse)(nil),    // 9: sam.v1.BootstrapEnrollResponse
	(*ServiceInfo)(nil),                // 10: sam.v1.ServiceInfo
	(*CommandBackend)(nil),             // 11: sam.v1.CommandBackend
	(*RegisterServiceRequest)(nil),     // 12: sam.v1.RegisterServiceRequest
	(*DiscoveredProvider)(nil),         // 13: sam.v1.DiscoveredProvider
	(*ServiceAnnounce)(nil),            // 14: sam.v1.ServiceAnnounce
	(*ControlPlaneInfoResponse)(nil),   // 15: sam.v1.ControlPlaneInfoResponse
	(*RouterLeaseRequest)(nil),         // 16: sam.v1.RouterLeaseRequest
	(*RouterLeaseResponse)(nil),        // 17: sam.v1.RouterLeaseResponse
	(*PolicyRole)(nil),                 // 18: sam.v1.PolicyRole
	(*PolicyBinding)(nil),              // 19: sam.v1.PolicyBinding
	(*PolicyConfigGetRequest)(nil),     // 20: sam.v1.PolicyConfigGetRequest
	(*PolicyConfigGetResponse)(nil),    // 21: sam.v1.PolicyConfigGetResponse
	(*PolicyConfigUpdateRequest)(nil),  // 22: sam.v1.PolicyConfigUpdateRequest
	(*PolicyConfigUpdateResponse)(nil), // 23: sam.v1.PolicyConfigUpdateResponse
	(*KeysResponse)(nil),               // 24: sam.v1.KeysResponse
	(*TokenRefreshRequest)(nil),        // 25: sam.v1.TokenRefreshRequest
	(*TokenRefreshResponse)(nil),       // 26: sam.v1.TokenRefreshResponse
	(*TokenRevokeRequest)(nil),         // 27: sam.v1.TokenRevokeRequest
	(*TokenRevokeResponse)(nil),        // 28: sam.v1.TokenRevokeResponse
	(*AgentSecret)(nil),                // 29: sam.v1.AgentSecret
	(*AgentEgress)(nil),                // 30: sam.v1.AgentEgress
	(*AgentIngress)(nil),               // 31: sam.v1.AgentIngress
	(*AgentBundle)(nil),                // 32: sam.v1.AgentBundle
	(*AgentAttachRequest)(nil),         // 33: sam.v1.AgentAttachRequest
	(*AgentAttachResponse)(nil),        // 34: sam.v1.AgentAttachResponse
	(*AgentDetachRequest)(nil),         // 35: sam.v1.AgentDetachRequest
	(*AgentDetachResponse)(nil),        // 36: sam.v1.AgentDetachResponse
	(*AgentRefreshRequest)(nil),        // 37: sam.v1.AgentRefreshRequest
	(*AgentRefreshResponse)(nil),       // 38: sam.v1.AgentRefreshResponse
	(*AgentStatusRequest)(nil),         // 39: sam.v1.AgentStatusRequest
	(*AgentStatus)(nil),                // 40: sam.v1.AgentStatus
	(*AgentStatusResponse)(nil),        // 41: sam.v1.AgentStatusResponse
	(*IdentityEvidenceResponse)(nil),   // 42: sam.v1.IdentityEvidenceResponse
	(*PeerEvidenceResponse)(nil),       // 43: sam.v1.PeerEvidenceResponse
	nil,                                // 44: sam.v1.EnrollRequest.LabelsEntry
	nil,                                // 45: sam.v1.BootstrapEnrollRequest.LabelsEntry
	nil,                                // 46: sam.v1.CommandBackend.EnvEntry
	nil,                                // 47: sam.v1.ServiceAnnounce.LabelsEntry
	nil,                                // 48: sam.v1.PeerEvidenceResponse.LabelsEntry
}
var file_api_sam_proto_depIdxs = []int32{
	2,  // 0: sam.v1.MeshEvent.type:type_name -> sam.v1.MeshEvent.Type
	44, // 1: sam.v1.EnrollRequest.labels:type_name -> sam.v1.EnrollRequest.LabelsEntry
	45, // 2: sam.v1.BootstrapEnrollRequest.labels:type_name -> sam.v1.BootstrapEnrollRequest.LabelsEntry
	0,  // 3: sam.v1.BootstrapEnrollResponse.status:type_name -> sam.v1.EnrollmentStatus
	1,  // 4: sam.v1.ServiceInfo.type:type_name -> sam.v1.ServiceType
	46, // 5: sam.v1.CommandBackend.env:type_name -> sam.v1.CommandBackend.EnvEntry
	10, // 6: sam.v1.RegisterServiceRequest.service:type_name -> sam.v1.ServiceInfo
	11, // 7: sam.v1.RegisterServiceRequest.command:type_name -> sam.v1.CommandBackend
	1,  // 8: sam.v1.ServiceAnnounce.type:type_name -> sam.v1.ServiceType
	47, // 9: sam.v1.ServiceAnnounce.labels:type_name -> sam.v1.ServiceAnnounce.LabelsEntry
	18, // 10: sam.v1.PolicyConfigGetResponse.roles:type_name -> sam.v1.PolicyRole
	19, // 11: sam.v1.PolicyConfigGetResponse.bindings:type_name -> sam.v1.PolicyBinding
	18, // 12: sam.v1.PolicyConfigUpdateRequest.roles:type_name -> sam.v1.PolicyRole
	19, // 13: sam.v1.PolicyConfigUpdateRequest.bindings:type_name -> sam.v1.PolicyBinding
	29, // 14: sam.v1.AgentEgress.secrets:type_name -> sam.v1.AgentSecret
	1,  // 15: sam.v1.AgentIngress.type:type_name -> sam.v1.ServiceType
	30, // 16: sam.v1.AgentBundle.egress:type_name -> sam.v1.AgentEgress
	31, // 17: sam.v1.AgentBundle.ingress:type_name -> sam.v1.AgentIngress
	32, // 18: sam.v1.AgentAttachRequest.bundle:type_name -> sam.v1.AgentBundle
	31, // 19: sam.v1.AgentStatus.ingress:type_name -> sam.v1.AgentIngress
	40, // 20: sam.v1.AgentStatusResponse.agents:type_name -> sam.v1.AgentStatus
	48, // 21: sam.v1.PeerEvidenceResponse.labels:type_name -> sam.v1.PeerEvidenceResponse.LabelsEntry
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_sam_proto_init() }
func file_api_sam_proto_init() {
	if File_api_sam_proto != nil {
		return
	}
	file_api_sam_proto_msgTypes[9].OneofWrappers = []any{
		(*RegisterServiceRequest_TargetUrl)(nil),
		(*RegisterServiceRequest_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sam_proto_rawDesc), len(file_api_sam_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_sam_proto_goTypes,
		DependencyIndexes: file_api_sam_proto_depIdxs,
		EnumInfos:         file_api_sam_proto_enumTypes,
		MessageInfos:      file_api_sam_proto_msgTypes,
	}.Build()
	File_api_sam_proto = out.File
	file_api_sam_proto_goTypes = nil
	file_api_sam_proto_depIdxs = nil
}
